package allureattachmenttests;

import allureattachmenttests.util.FileUtil;
import io.qameta.allure.Attachment;
import org.testng.annotations.Test;

import java.io.File;

public class StringAttachTest {

    @Test(description = "checking String attachment with allure")
    public void checkAllureAttachments() {
        getExpectedName();
        getEnvValue();
        getOsEnvValue();
//        testFileGen();
    }

    @Attachment("expected name :")
    private String getExpectedName() {
        return "Apple MacBook Pro 16";
    }

    @Attachment("Java Environment :")
    private String getEnvValue() {
        return System.getenv("JAVA_HOME");
    }

    @Attachment("OS Info :")
    private String getOsEnvValue() {
        return attachOSInfo();
    }

    @Attachment(value = "Generated text file :", type = "text")
    public File testFileGen() {
        String fileName = "src/main/resources/output.txt";
        String content = "This is a sample text file generated by TestNG.";
        File generatedFile = FileUtil.writeToFile(fileName, content);
        return generatedFile;
    }

    private String attachOSInfo() {
        return "OS: " + System.getProperty("os.name") +
                "\nVersion: " + System.getProperty("os.version") +
                "\nArchitecture: " + System.getProperty("os.arch");
    }
}
