package allureattachmenttests;

import allureattachmenttests.util.FileUtil;
import io.qameta.allure.Attachment;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class TextFileAttachTest {
    private final String fileName = "src/main/resources/output.txt";

    @Attachment(value = "Generated Text File", type = "text/plain")
    public String attachFile(String content) {
        return content;
    }

    @Test(description = "checking text file attachment with allure")
    public void testFileGeneration() {
        String content = "This is a sample text file generated by TestNG.";
        File generatedFile = FileUtil.writeToFile(fileName, content);

        if (generatedFile != null) {
            try {
                // Read the content of the file
                String fileContent = new String(Files.readAllBytes(generatedFile.toPath()));
                attachFile(fileContent); // Attach the content
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    @AfterMethod(alwaysRun = true)
    public void cleanup() {
        try {
            Files.deleteIfExists(Path.of(fileName));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
